"""Scanner watchlists — pre-market uses 10 curated stocks, daily scan uses top 100."""

# 23 highly liquid mid-to-large caps in ₹400–₹2000 range for the Trading screen
TRADING_LIST = [
    "ICICIBANK","AXISBANK","SBIN","HCLTECH","WIPRO",
    "TECHM","DRREDDY","CIPLA","SUNPHARMA","TATAMOTORS",
    "HDFCBANK","BHARTIARTL","BAJFINANCE","HINDALCO","ADANIPORTS",
    "JSWSTEEL","INDUSINDBK","SHRIRAMFIN","TATACONSUM","COALINDIA",
    "PIDILITIND","DLF","IRCTC",
]

# Pre-market auction (9:00–9:08): liquid F&O stocks in ₹1000–₹2500 range
WATCHLIST = [
    "RELIANCE","HDFCBANK","ICICIBANK","INFY","AXISBANK",
    "SUNPHARMA","TECHM","CIPLA","BAJAJFINSV","ADANIPORTS",
    "HCLTECH","KOTAKBANK","HINDUNILVR","ASIANPAINT","GRASIM",
]

# Daily live scan (9:15+): top 100 liquid NSE stocks by market cap
WATCHLIST_DAILY = [
    # Nifty 50
    "RELIANCE","TCS","HDFCBANK","ICICIBANK","INFY","HINDUNILVR","WIPRO",
    "BHARTIARTL","LT","KOTAKBANK","HCLTECH","SBIN","BAJFINANCE","AXISBANK",
    "ASIANPAINT","MARUTI","SUNPHARMA","BAJAJFINSV","TITAN","TATAMOTORS",
    "NTPC","POWERGRID","ULTRACEMCO","ADANIPORTS","ADANIENT","COALINDIA",
    "ONGC","NESTLEIND","GRASIM","JSWSTEEL","TATASTEEL","TATACONSUM",
    "HINDALCO","HDFCLIFE","SBILIFE","EICHERMOT","CIPLA","DIVISLAB",
    "APOLLOHOSP","DRREDDY","HEROMOTOCO","BRITANNIA","BAJAJ-AUTO",
    "INDUSINDBK","TECHM","LTIM","SHRIRAMFIN","UPL","VEDL","BEL",
    # Nifty Next 50 / large mid-cap
    "BANKBARODA","BOSCHLTD","CHOLAFIN","CUMMINSIND","DABUR","DLF",
    "GAIL","GODREJCP","GODREJPROP","HAVELLS","ICICIPRULI","INDHOTEL",
    "IOC","IRCTC","JINDALSTEL","LUPIN","MPHASIS","NAUKRI","NMDC",
    "OFSS","PAGEIND","PIDILITIND","PNB","RECLTD","SBICARD","SIEMENS",
    "SRF","TATACOMM","TORNTPHARM","TRENT","VBL","ZOMATO","ZYDUSLIFE",
    "MOTHERSON","BALKRISIND","COLPAL","BERGEPAINT","CONCOR","FORTIS",
    "AMBUJACEM","PIIND","ABBOTINDIA","ATGL","MCDOWELL-N","TATAPOWER",
    "ADANIGREEN","SAIL","PFC","NHPC","M&M",
]
