"""Scanner watchlist — shared between backend and frontend."""

WATCHLIST = [
    "RELIANCE","TCS","HDFCBANK","ICICIBANK","INFY","HINDUNILVR",
    "BAJFINANCE","AXISBANK","KOTAKBANK","LT","ASIANPAINT","MARUTI","SUNPHARMA",
    "DRREDDY","TECHM","ULTRACEMCO","TITAN","NESTLEIND","DIVISLAB",
    "CIPLA","BAJAJFINSV","ADANIPORTS","GRASIM","HEROMOTOCO","EICHERMOT",
    "BRITANNIA","PIDILITIND",
]
