"""Scanner watchlist — shared between backend and frontend."""

WATCHLIST = [
    "RELIANCE","TCS","HDFCBANK","ICICIBANK","INFY","HINDUNILVR","ITC","SBIN",
    "BAJFINANCE","AXISBANK","KOTAKBANK","LT","ASIANPAINT","MARUTI","SUNPHARMA",
    "DRREDDY","WIPRO","TECHM","ULTRACEMCO","TITAN","NESTLEIND","POWERGRID","NTPC",
    "ONGC","TATAMOTORS","TATASTEEL","JSWSTEEL","HINDALCO","COALINDIA","DIVISLAB",
    "CIPLA","BAJAJFINSV","ADANIPORTS","GRASIM","HEROMOTOCO","EICHERMOT","BPCL",
    "VEDL","BRITANNIA","PIDILITIND",
]
